# Generated by Django 3.2.15 on 2022-08-11 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20220809_1739'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
            ],
            options={
                'db_table': 'userinfo',
            },
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
